version: '3.8'

services:
  # OmniFoundry API 服務（CPU 版本）
  omnifoundry-cpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: omnifoundry-cpu
    ports:
      - "8000:8000"
    volumes:
      # 掛載模型緩存目錄
      - ./models:/app/models
      # 掛載配置檔
      - ./configs:/app/configs
    environment:
      - OMNIFOUNDRY_CONFIG=/app/configs/default.yaml
      - FORCE_CPU=true
    restart: unless-stopped
    command: omnifoundry serve --host 0.0.0.0 --port 8000

  # OmniFoundry API 服務（GPU 版本）
  omnifoundry-gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: omnifoundry-gpu
    ports:
      - "8001:8000"
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
    environment:
      - OMNIFOUNDRY_CONFIG=/app/configs/default.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: omnifoundry serve --host 0.0.0.0 --port 8000
    profiles:
      - gpu

networks:
  default:
    name: omnifoundry-network

